version: v1
plugins:
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2
    out: api/docs
    opt:
      - allow_repeated_fields_in_body=true
      # - output_format=yaml
      - allow_merge=true
      - merge_file_name=docs
      - openapi_naming_strategy=simple
