// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: demo/bar/v1/service.proto

package barv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// define the regex for a UUID once up-front
var _service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetDrinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetDrinkRequest) Validate() error {
	if m == nil {
		return nil
	}

	if err := m._validateUuid(m.GetName()); err != nil {
		return GetDrinkRequestValidationError{
			field:  "Name",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	return nil
}

func (m *GetDrinkRequest) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetDrinkRequestValidationError is the validation error returned by
// GetDrinkRequest.Validate if the designated constraints aren't met.
type GetDrinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDrinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDrinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDrinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDrinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDrinkRequestValidationError) ErrorName() string { return "GetDrinkRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetDrinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDrinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDrinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDrinkRequestValidationError{}

// Validate checks the field values on GetDrinkResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetDrinkResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Message

	return nil
}

// GetDrinkResponseValidationError is the validation error returned by
// GetDrinkResponse.Validate if the designated constraints aren't met.
type GetDrinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDrinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDrinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDrinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDrinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDrinkResponseValidationError) ErrorName() string { return "GetDrinkResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetDrinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDrinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDrinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDrinkResponseValidationError{}
